### ISSUE TITLE
Checklist before we can distribute to 3P Devs

### ISSUE THREAD

**Issue by mikkoh** [Shopify/unity-buy-sdk#33]
The following should be completed before sending `.unitypackage` to 3p developer
- [x] Documentation
- [x] Move Input objects to `Shopify.Unity`
- [x] Merge in creating permalinks + cart #32 
- [x] Ensure `Init` does not create a second client (fixed in #32)
- [x] Create new `.unitypackage`
