### ISSUE TITLE
[UI toolkit] Product list view todo / bugs

### ISSUE THREAD

**Issue by richardmonette** [Shopify/unity-buy-sdk#490]
- [ ] Loading states, for when more products are being added to the list
- [ ] Elastic / momentum scrolling
- [ ] Fix images still popping into view in some cases
- [ ] Fix scroll offset limit so last element comes fully into view

cc @JakeCataford @sleroux
